Running getd benchmark
Wed Nov 13 04:28:29 PM UTC 2024
Traceback (most recent call last):
  File "/home/fedora/einsum_ir/samples/tensor_decomp/getd_tvm.py", line 45, in <module>
    tvm_helper.run_all( einsum_str,
  File "/home/fedora/einsum_ir/samples/tools/tvm_helper.py", line 252, in run_all
    str(rel_error),
NameError: name 'rel_error' is not defined
Wed Nov 13 05:20:41 PM UTC 2024
